---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: wishpost-platform-data-engine-api-worker
  namespace: wish-micro
  annotations:
    fluxcd.io/automated: "true"
    # This will be changed by Setonix automatically.
    filter.fluxcd.io/chart-image: "*"
spec:
  releaseName: wishpost-platform-data-engine-api-worker
  chart:
    git: git@github.com:ContextLogic/helm-ms-cn.git
    path: charts/simple-worker
    ref: dev
  values:
    image:
      repository: harbor.infra.wish-cn.com/wish/wishpost-platform-data-engine-api/api
      tag: <tag>
    fullnameOverride: wishpost-platform-data-engine-api-worker
    port: 5558
    wishAppLabel: wishpost-platform-data-engine-api
    serviceAccount:
      create: false
      # If you are using aws resources, e.g. SQS and S3,
      # please create a Jira ticket to SRE @yiyan to ask for role-arn.
      #annotations:
      #  eks.amazonaws.com/role-arn: <role-arn>
      #  eks.amazonaws.com/audience: sts.amazonaws.com.cn
    podAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: "5558"
      co.elastic.logs/enabled: 'true'
    env:
      - name: C_FORCE_ROOT
        value: "True"
      - name: FLASK_ENV
        value: dev
    args:
      - /bin/bash
      - -c
      - "/production/wishpost-platform-data-engine-api/current/wishpost-platform-data-engine-api/bin/entrypoint-worker.sh"
